config/routes.rb
Delice::Application.routes.draw do
resources :users
resources :sessions, only: [:new, :create, :destroy, :failure]

root to: 'static_pages#home'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  match '/auth/destroy', :to => 'sessions#destroy'
  match '/home', to: 'static_pages#home'
  match '/faq', to: 'static_pages#faq'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id, :user
  belongs_to :user
  validates :provider, :uid, :presence => true

  def self.find_or_create(auth_hash)
    unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      user = User.create :name => auth_hash["info"]["name"], :email => auth_hash["info"]["email"]
      auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
    auth
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :authorizations
  validates :name, :email, :presence => true

  def add_provider(auth_hash)
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth_hash = get_auth_hash
    if session[:user_id]
      User.find(session[:user_id]).add_provider(auth_hash)
    else
      auth = Authorization.find_or_create(auth_hash)
      session[:user_id] = auth.user.id
    end
    redirect_back_or auth.user
  end

  def failure
    flash[:error] = "Sorry, but you didn't allow access to our app!"
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  protected

  def get_auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Delice - Home Cooked Meals Done Right"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def sign_out
    session[:user_id] = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li>&copy; Delice </li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Jobs", '#' %></li>
      <li><%= link_to "FAQ", faq_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Delice", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Browse Listings", '#' %></li>
          <li><%= link_to "How it works", '#' %></li>
          <li><%= link_to "Our Team", '#' %></li>
          <li><%= link_to "Chef Application", '#' %></li>
          <% if session[:user_id] %>
            <li><%= link_to "Sign out", auth_destroy_path %></li>
          <% else %>
            <li><%= link_to "Sign in", "/auth/facebook/" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="vcard">
  <p class="adr">
    <span class="street-address">Abhishek Sen</span><br>
    <span class="street-address">1540 Maurice Lane, Apt 47</span><br>
    <span class="region">San Jose</span><br>
    <span class="postal-code">CA 95129</span><br>
    <span class="country-name">USA</span>
  </p>
  <p class="tel">+1 408 406 4578</p>
</div>

app/views/static_pages/faq.html.erb
<div class="center">
  <p>Here are answers to some common questions</p>
</div>

app/views/static_pages/home.html.erb
<body>
    <div class="span12 welcome-image">
    <div id="myCarousel" class="carousel slide">
      <div class="carousel">
        <div class="active item">
          <img src="assets/home/tikka.jpg" alt="Chicken Tikka" height="700" width="1100"/>
        </div>
        <div class="item">
          <img src="assets/home/lasagna.jpg" alt="Lasagna" height="700" width="1100"/>
        </div>
        <div class="item">
          <img src="assets/home/pasta.jpg" alt="Pasta" height="700" width="1100"/>
        </div>
      </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
</body>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="row">
  <div class="span8">
    <h1>Welcome back <%= @user.name %>!</h1>
    <h2>Your current email is <%= @user.email %></h2>
  </div>
</div>